### ISSUE TITLE
FE & game : 키보드 입력을 중복으로 받음

### ISSUE THREAD

**Issue by 42JINAM** [God-save-the-carrots/ft_transcendence#115]
유저의 닉네임 입력을 받는 것 까지 완성함 

하지만 이벤트를 감지할때 게임에서도 키보드 입력을 받는데 닉네임 입력할때도 감지하고 있음

**Comment by sindydwns** [comment]
아직 소켓이 연결되지 않은 게임은 키 입력을 사용하지 않도록 수정 완료
