### ISSUE TITLE
Minor - 다국어 지원

### ISSUE THREAD

**Issue by iijung** [God-save-the-carrots/ft_transcendence#52]
# 다국어 지원

이 마이너 모듈의 목표는 귀하의 웹사이트가 다양한 사용자 기반을 충족하기 위해 여러 언어를 지원하는지 확인하는 것입니다. 주요 기능과 목표는 다음과 같습니다.

- [x] 광범위한 청중을 수용하기 위해 웹사이트에서 최소 3개 언어에 대한 지원을 구현합니다.
- [x] 사용자가 자신의 기본 설정에 따라 웹사이트의 언어를 쉽게 변경할 수 있는 언어 전환기 또는 선택기를 제공합니다.
- [x] 탐색 메뉴, 제목, 주요 정보 등 필수 웹사이트 콘텐츠를 지원되는 언어로 번역합니다.
- [x] 선택한 언어에 관계없이 사용자가 웹 사이트를 원활하게 탐색하고 상호 작용할 수 있는지 확인합니다.
- [x] 번역 프로세스를 단순화하고 다양한 언어 간 일관성을 유지하려면 언어 팩이나 지역화 라이브러리를 사용하는 것이 좋습니다.
- [x] 사용자가 나중에 웹 사이트를 방문할 때 기본 선택으로 선호하는 언어를 설정할 수 있도록 허용합니다.

이 마이너 모듈은 콘텐츠를 여러 언어로 제공하여 웹사이트의 접근성과 포괄성을 향상시켜 다양한 국제 청중이 더욱 사용자 친화적으로 만드는 것을 목표로 합니다.

**Comment by 42JINAM** [comment]
언어 선택기는 네비바에 붙이는게 맞는것 같아서 네비바에 일단 붙여서 테스트 했는데, 위치나 디자인은 채서님께 부탁 드립니다. 

유저가 설정한 언어로 항상 먼저 보여주기 위해 
로그인 후에 백엔드에 언어를 저장하고 보여줄 필요가 있을 것 같습니다 

@moaoh @veggie-garden
