### ISSUE TITLE
backend api 수정필요

### ISSUE THREAD

**Issue by 42JINAM** [God-save-the-carrots/ft_transcendence#87]
- [x] `http://localhost:8000/api/game/pong/matches/11/` api에서 각 round마다 start_time and end_time data 필요
- [x] `http://localhost:8000/api/game/pong/score/dumm1/?page=0&page_size=1` page index가 1부터 시작하도록 수정필요
- [x] `http://localhost:8000/api/game/pong/matches/11/` game에서 round_2가 항상 최상단데이터로 들어오게 수정필요

**Comment by moaoh** [comment]
수정완료된 issue 이므로 close 진행하였습니다.
