### ISSUE TITLE
프론트 게임 닉네임 설정 기능 추가..?

### ISSUE THREAD

**Issue by 42JINAM** [God-save-the-carrots/ft_transcendence#95]
꼭 해야 하는 것 인지 확실 하지는 않음 

프론트에서 버튼으로 닉네임을 설정 할 수 있도록 받고, 게임에서 이것을 반영할 수 있는 함수를 지원해주면 프론트에서 기능 구현 가능 할 것 이라 생각됨 (난이도 약간 하)

**Comment by iijung** [comment]
점수를 받지는 않기로 했지만 유저 관리 모듈로 인해 요구사항 변경이 가능하므로 닉네임을 intraid로 대체해도 괜찮다고 생각합니다.

**Comment by iijung** [comment]
- #32 

충족은 못 했지만... 해당 모듈을 선택했지만 완성은 못 했으니 점수는 받지 않는 걸로 디펜스 하신다고 하셨던거로 기억합니다.

**Comment by 42JINAM** [comment]
ㅋㅋ 그런 이야기를 했던 것은 기억이 납니다. 그런데 모듈의 일부만 하다말았다고 하는게 디펜스 가능할지...!!?!!??! 이거 월욜에 한번 이야기 다시 해볼가여? 디펜스와 구현 사이 비용 문제에 대해서용

**Comment by 42JINAM** [comment]
구현 완료 !

**Comment by iijung** [comment]
이슈 완료했을 때 다음과 같이 해주시면 더 좋을 것 같아요!

1. `- #번호` 로 풀 리퀘스트 연결
2. `abc4242`와 같은 해시 태그로 커밋 연결

**Comment by 42JINAM** [comment]
앗 녭!

**Comment by iijung** [comment]
바로 반영해주시다니 멋져요 👏 👏 👏
